In [1]:
import torch
import numpy as np

In [2]:
X = torch.tensor([
  [1, 2, 3],
  [4, 5, 6]
])

In [3]:
X

tensor([[1, 2, 3],
        [4, 5, 6]])

In [4]:
X.shape

torch.Size([2, 3])

In [5]:
y = X[:, :, None]

In [6]:
y.shape

torch.Size([2, 3, 1])

In [7]:
y

tensor([[[1],
         [2],
         [3]],

        [[4],
         [5],
         [6]]])

In [8]:
X.reshape(6).reshape(1, 2, 3)

tensor([[[1, 2, 3],
         [4, 5, 6]]])

In [17]:
t=torch.tensor([[1,2, 3],[4, 5, 6], [7,8,9], [10,11,12]])
r=torch.randperm(2)
c=torch.randperm(3)
t=t[r, :]

# With view
# idx = torch.randperm(t.nelement())
# t = t.view(-1)[idx].view(t.size())

In [16]:
t

tensor([[4, 5, 6],
        [1, 2, 3]])

In [20]:
indices = torch.randperm(t.shape[0])[:2]

t[indices]

tensor([[4, 5, 6],
        [1, 2, 3]])