In [2]:
import torch
import numpy as np

In [3]:
X = torch.tensor([
  [1, 2, 3],
  [4, 5, 6]
])

In [4]:
X

tensor([[1, 2, 3],
        [4, 5, 6]])

In [5]:
X.shape

torch.Size([2, 3])

In [7]:
y = X[:, :, None]

In [8]:
y.shape

torch.Size([2, 3, 1])

In [13]:
y

tensor([[[1],
         [2],
         [3]],

        [[4],
         [5],
         [6]]])

In [17]:
X.reshape(6).reshape(1, 2, 3)

tensor([[[1, 2, 3],
         [4, 5, 6]]])